### ISSUE TITLE
fieldVectors or documentVectors?

### ISSUE THREAD

**Issue by gerwitz** [olivernn/lunr-schema#1]
This documentation says "fieldVector" but my serialized indexes from 2.0.3 say "documentVector"

**Comment by olivernn** [comment]
This schema was extracted from version 2.1.x of Lunr, there was a [change](https://github.com/olivernn/lunr.js/issues/263) that fixed some issues with field based searching/boosts.

If you upgrade to 2.1 then the schema here should match the serialised index, if it doesn't then please let me know.

**Comment by gerwitz** [comment]
Ah, thank you. I'm using a fork of https://github.com/manastech/middleman-search/ that's only on 2.0.3, and this repo says "2.x" so I blindly assumed.

(I was going to read the index directly for some visualization, but this experience helped me decide to restrict myself to lunr's API.)

**Comment by olivernn** [comment]
The idea of this repo was to have something published and public that described the schema of the serialised format. It _should_ be possible for you to build tools based on this schema.

That said this is still a WIP, but it does describe exactly the schema from Lunr 2.1 and up.
